name: Man10Forex
version: '1.0'
main: red.man10.man10forex.Man10Forex
softdepend:
  - Man10Bank
  - Man10CommonLibs
api-version: 1.19
commands:
  mhl:
    default: op
  mfx:
    default: op
  zfx:
    default: op